In [2]:
import numpy as np

a = np.array([[300, -100, 0, 0, 0],
             [-100, 200, -100, 0, 0],
             [0, -100, 200, -100, 0],
             [0, 0, -100, 200, -100],
             [0, 0, 0, -100, 300]])

In [3]:
a

array([[ 300, -100,    0,    0,    0],
       [-100,  200, -100,    0,    0],
       [   0, -100,  200, -100,    0],
       [   0,    0, -100,  200, -100],
       [   0,    0,    0, -100,  300]])

In [5]:
TA = 100
TB = 500
b = np.array([200*TA,0,0,0,200*TB])

In [7]:
np.linalg.solve(a,b)

array([140., 220., 300., 380., 460.])

In [9]:
a.shape

(5, 5)

In [10]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])